{
    'name': 'Ramina Custom Payroll',
    'version': '19.0.1.0.0',
    'category': 'Human Resources/Payroll',
    'summary': 'Minimal Payroll Engine & Overtime tracking for Ramina',
    'description': 'Provides a custom minimal payroll engine (hr.payslip) with automatic overtime tracking for Odoo Community.',
    'author': 'Ramina',
    'license': 'LGPL-3',
    'depends': ['hr', 'hr_attendance', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/hr_overtime_cron.xml',
        'views/hr_overtime_bonus_views.xml',
        'views/hr_payslip_views_custom.xml',
        'views/hr_employee_views_custom.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
